
/*******************************************************************************
* generated by lcd-image-converter rev.129188f from 2019-07-09 00:20:51 +0500
* image
* filename: unsaved
* name: TEMP
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Threshold Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t image_data_TEMP[20] = {
    // ██∙███████
    // █∙█∙██████
    // █∙█∙██████
    // █∙∙∙██████
    // █∙∙∙██████
    // ∙∙∙∙∙█████
    // ∙∙∙∙∙█████
    // █∙∙∙██████
    // ██████████
    // ██████████
    0xdf, 0xc0, 
    0xaf, 0xc0, 
    0xaf, 0xc0, 
    0x8f, 0xc0, 
    0x8f, 0xc0, 
    0x07, 0xc0, 
    0x07, 0xc0, 
    0x8f, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
const tImage TEMP = { image_data_TEMP, 10, 10,
    8 };

